[dependencies]
common-error = {path = "../common-error", default-features = false}
daft-core = {path = "../daft-core", default-features = false}
daft-dsl = {path = "../daft-dsl", default-features = false}
daft-io = {path = "../daft-io", default-features = false}
daft-table = {path = "../daft-table", default-features = false}
indexmap = "2.0.0"
snafu = "0.7.4"

[features]
default = ["python"]
python = ["dep:pyo3", "common-error/python", "daft-core/python", "daft-dsl/python", "daft-io/python", "daft-table/python"]

[package]
edition = "2021"
name = "daft-plan"
version = "0.1.10"

[dependencies.arrow2]
git = "https://github.com/Eventual-Inc/arrow2"
package = "arrow2"
rev = "2834446a10545156bdf9c2898577e87e07d4d42d"
version = "0.17.1"
features = ["chrono-tz", "compute_take", "compute_cast", "compute_aggregate", "compute_if_then_else", "compute_sort", "compute_filter", "compute_temporal", "compute_comparison", "compute_arithmetics", "compute_concatenate", "io_ipc"]

[dependencies.bincode]
version = "1.3.3"

[dependencies.pyo3]
features = [ "extension-module", "multiple-pymethods", "abi3-py37",]
version = "0.19.1"
optional = true

[dependencies.serde]
features = [ "derive", "rc","rc",]
version = "1.0.179"
