[tool.poetry]
name = "i-saas-utils"
version = "0.1.8"
description = ""
authors = ["Fedorov Stepan <fedorov.stepan2@wb.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
jinja2 = "^3.1.2"
kubernetes = "^27.2.0"
gitpython = "^3.1.32"
python-gitlab = "^3.15.0"
dnspython = "^2.4.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
