[tool.poetry]
name = "mirror-api"
version = "1.2.0"
description = "An API that returns the structure of the request as the response"
authors = ["Nick DeRobertis <derobertis.nick@gmail.com>"]
readme = "README.md"
packages = [{include = "mirror_api"}]
license = "MIT"
classifiers = [
    # How mature is this project? Common values are
    #   3 - Alpha
    #   4 - Beta
    #   5 - Production/Stable
    "Development Status :: 3 - Alpha",
    # Indicate who your project is intended for
    "Intended Audience :: Developers",
    # List supported python versions
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
include = ["conf.py", "version.py"]

[tool.poetry.urls]
repository = "https://github.com/nickderobertis/mirror-api"
documentation = "https://nickderobertis.github.io/mirror-api"

[tool.setuptools]
packages = ["mirror_api"]

[tool.poetry.scripts]
mirror-api = "mirror_api.__main__:main"

[tool.poetry.dependencies]
python = ">=3.8"
fastapi = "*"
uvicorn = {extras = ["standard"], version = "*"}
typer = "*"
python-multipart = "*"

[tool.poetry.group.test.dependencies]
pytest = "*"
pytest-cov = "*"
httpx = "^0.24.1"
anyio = "^3.7.1"

[tool.black]
include = 'mirror_api.*\.pyi?$|tests.*\.pyi?$'

[tool.isort]
profile = "black"
skip = ['.bzr', '.direnv', '.eggs', '.git', '.hg', '.mypy_cache', '.pants.d', '.svn', '.tox', '.venv', '__pypackages__', '_build', 'buck-out', 'build', 'dist', 'node_modules', '.venvs']
