agent:
  name: Sarah
general:
  logging_level: ERROR
  logging_haystack_level: ERROR
  pytorch_cuda_config: max_split_size_mb:21
  welcome: true
model:
  id: meta-llama/Llama-2-7b-chat-hf
  token: HUGGINGFACE_TOKEN
  token_length: 1000
socket:
  REP: tcp://*:12443
  REQ: tcp://localhost:12443
