[project]
name = "ckanext-restricted_api"
dynamic = []
description = "Extension to allow dataset restriction via CKAN API."
authors = [
    { name = "Sam Woodcock", email = "sam.woodcock@protonmail.com" },
]
dependencies = []
requires-python = ">=3.8"
readme = "README.md"
keywords = [
    "CKAN",
    "restricted",
    "access",
    "authorization",
    "envidat",
]
classifiers = [
    "Topic :: Utilities",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
]
version = "2.0.6"

[project.license]
text = "MIT"

[project.entry-points."ckan.plugins"]
restricted_api = "ckanext.restricted_api.plugin:RestrictedAPIPlugin"

[project.urls]
homepage = "https://gitlabext.wsl.ch/EnviDat/ckanext-restricted_api.git"
documentation = "https://envidat.gitlab-pages.wsl.ch/ckanext-restricted_api"
repository = "https://gitlabext.wsl.ch/EnviDat/ckanext-restricted_api.git"

[build-system]
requires = [
    "pdm-pep517>=1.0.0",
]
build-backend = "pdm.pep517.api"

[tool.pdm]
includes = [
    "ckanext",
]
source-includes = [
    "ckanext/restricted_api/tests",
    "CHANGELOG.md",
]
source = [
    { name = "pypi", url = "https://pypi.org/simple", verify_ssl = true },
]

[tool.pdm.version]
from = "ckanext/restricted_api/__version__.py"

[tool.pdm.dev-dependencies]
dev = [
    "pytest-ckan>=0.0.12",
]

[tool.commitizen]
name = "cz_conventional_commits"
version = "2.0.6"
version_files = [
    "pyproject.toml:version",
    "ckanext/restricted_api/__version__.py",
    "docs/openapi.yaml:version",
]

[tool.isort]
profile = "black"
atomic = true
known_first_party = [
    "ckanext",
]

[tool.ruff]
target-version = "py38"
line-length = 88
select = [
    "I",
    "E",
    "W",
    "D",
    "B",
    "F",
    "N",
    "Q",
]
exclude = [
    ".git",
    ".ruff_cache",
    ".vscode",
    "__pypackages__",
    "build",
    "dist",
    "migrations",
    "ckanext/restricted_api/__version__.py",
]

[tool.ruff.pydocstyle]
convention = "google"

[tool.pytest.ini_options]
addopts = "-ra -q"
testpaths = [
    "tests",
]
