[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "enkidu-ds"
version = "0.0.4"
authors = [
  { name="Daniel Kaczmarczyk", email="daniel.kacz@protonmail.com" },
]
description = "Collection of implementations of data structures and algorithms that operate on them"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/danielkaczmarczyk/enkidu"
"Bug Tracker" = "https://github.com/danielkaczmarczyk/enkidu/issues"


