[project]
name = "campbells"
dynamic = []
description = "A condensed web scraping library."
authors = [
    { name = "Louis Maddox", email = "louismmx@gmail.com" },
]
keywords = [
    "HTML",
    "XML",
    "parse",
    "soup",
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Topic :: Software Development :: Libraries",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Text Processing :: Markup :: HTML",
    "Topic :: Text Processing :: Markup :: SGML",
    "Topic :: Text Processing :: Markup :: XML",
]
dependencies = [
    "pydantic>=2.1.1",
    "beautifulsoup4>=4.12.2",
]
requires-python = ">=3.10"
readme = "README.md"
version = "0.1.1"

[project.license]
text = "MIT"

[project.optional-dependencies]
html5lib = [
    "html5lib>=1.1",
]
lxml = [
    "lxml>=4.9.3",
]

[project.urls]
Homepage = "https://github.com/lmmx/campbells"
Repository = "https://github.com/lmmx/campbells.git"

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.pdm.version]
source = "file"
path = "src/campbells/__init__.py"

[tool.pdm.dev-dependencies]
test = [
    "pytest>=7.4.0",
]

[tool.isort]
known_first_party = [
    "campbells",
]
