[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "lvdb"
version = "1.0.3"
authors = [
  { name="TripIe", email="TripIe@test.com" },
]
description = "A package to locally shard vector data to conserve memory in memory-limited environments"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]