[tool.poetry]
name = "bsdm"
version = "0.9.0"
description = "Beautiful SVG Data Model"
authors = ["Lo√Øc BAUD <loic.baud@tnpconsultants.com>"]
readme = "README.md"
packages = [
	{include = "bsdm"},
	{include = "bsdm/classes/*.py"},
	{include = "bsdm/utils/*.py"}
]

[tool.poetry.dependencies]
python = "^3.11"
svgwrite = "^1.4.3"
argparse = "^1.4.0"
pathlib = "^1.0.1"
logging = "^0.4.9.6"
tk = "^0.1.0"
regex = "^2023.8.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
