# pyproject.toml

[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "neuralpit"
version = "3.4.6"
description = "NeuralPit SDK"
readme = "README.md"
authors = [{ name = "Quang Nguyen", email = "quang.nguyen@neuralpit.com" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["api", "neural", "neuralpit"]
dependencies = [
    "requests",
    "langchain==v0.0.230",
    "lxml",
    "openai",
    "tiktoken",
    "bs4",
    "qdrant-client",
    "boto3",
    "PyMuPDF",
    "unstructured[docx,xlsx,pptx,doc,xls,ppt]",
    "email-validator",
    "scrapy",
    "pytube",
    "youtube-transcript-api",
    "pandas",
    "numpy",
    "astor",
    "matplotlib"
]

requires-python = ">=3.9"

[project.optional-dependencies]
dev = ["black", "bumpver", "isort", "pip-tools", "pytest"]

[tool.bumpver]
current_version = "2023.1001-alpha"
version_pattern = "YYYY.BUILD[-TAG]"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = true

[tool.bumpver.file_patterns]
"pyproject.toml" = ['current_version = "{version}"', 'version = "{version}"']
